server:
  port: 8080

spring:
  application:
    name: sto-service

  datasource:
    url: jdbc:postgresql://db:5432/sto_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      request:
        topic: request-events
        group: sto-group
    listener:
      missing-topics-fatal: false

logging:
  level:
    root: INFO
    kz.sto.car_service: DEBUG