server:
  port: 8080

spring:
  application:
    name: sto-service

  datasource:
    url: jdbc:postgresql://db:5432/sto_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: kafka:9092

    consumer:
      request:
        topic: request-events
        group: sto-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      client-id: sto-service-producer-1

    listener:
      missing-topics-fatal: false

logging:
  level:
    root: INFO
    kz.sto.car_service: DEBUG